dym: use fn_addr_eq for function pointer comparison (#44654)
Small fix to rust dynamic modules SDK.

Came across this issue when trying to bump [dynamic-modules-examples to
1.38.0](https://github.com/envoyproxy/dynamic-modules-examples/pull/61):

```
error: function pointer comparisons do not produce meaningful results since their addresses are not guaranteed to be unique
  --> src/lib.rs:66:1
   |
66 | / declare_all_init_functions!(init,
67 | |     http: new_http_filter_config_fn,
68 | |     network: new_network_filter_config_fn,
69 | |     udp_listener: new_udp_listener_filter_config_fn
70 | | );
   | |_^
   |
   = note: the address of the same function can vary between different codegen units
   = note: furthermore, different functions could have the same address after being merged together
   = note: for more information visit <https://doc.rust-lang.org/nightly/core/ptr/fn.fn_addr_eq.html>
   = note: this error originates in the macro `envoy_proxy_dynamic_modules_rust_sdk::set_factory_once` which comes from the expansion of the macro `declare_all_init_functions` (in Nightly builds, run with -Z macro-backtrace for more info)
```


<!--
!!!ATTENTION!!!

If you are fixing *any* crash or *any* potential security issue, *do
not*
open a pull request in this repo. Please report the issue via emailing
envoy-security@googlegroups.com where the issue will be triaged
appropriately.
Thank you in advance for helping to keep Envoy secure.

!!!ATTENTION!!!

For an explanation of how to fill out the fields, please see the
relevant section
in
[PULL_REQUESTS.md](https://github.com/envoyproxy/envoy/blob/main/PULL_REQUESTS.md)

!!!ATTENTION!!!

Please check the [use of generative AI
policy](https://github.com/envoyproxy/envoy/blob/main/CONTRIBUTING.md?plain=1#L41).

You may use generative AI only if you fully understand the code. You
need to disclose
this usage in the PR description to ensure transparency.
-->

Commit Message: dym: use fn_addr_eq for function pointer comparison
Additional Description: 
Risk Level: Low
Testing: N/A
Docs Changes:
Release Notes:
Platform Specific Features:
[Optional Runtime guard:]
[Optional Fixes #Issue]
[Optional Fixes commit #PR or SHA]
[Optional Deprecated:]
[Optional [API
Considerations](https://github.com/envoyproxy/envoy/blob/main/api/review_checklist.md):]

Signed-off-by: Gal Ovadia <ggalovadia@gmail.com>